# Generated by Django 4.1 on 2024-11-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='precio_unitario',
        ),
    ]
